/*****************************************************************************
* Model: coffeeAo.qm
* File:  src\coffee/alarm.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/2) .................................................................*/
#include "qp_port.h"
#include "coffee.h"
#include "alarm.h"

extern CoffeeAO l_CoffeeAO;

/* @(/2/3) .................................................................*/
void Alarm_ctor(Alarm * me) {
    QHsm_ctor(&me->super, (QStateHandler)&Alarm_initial);
}
/* @(/2/1) .................................................................*/
/* @(/2/1/3) ...............................................................*/
/* @(/2/1/3/0) */
QState Alarm_initial(Alarm * const me, QEvt const * const e) {
    return Q_TRAN(&Alarm_alarm_off);
}
/* @(/2/1/3/1) .............................................................*/
QState Alarm_normal(Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/1/3/1/0) */
        case TIME_SET_SIG: {
            printf("setting time\n");
            Write_RTC( &((RtcEvt*)e)->rtc );
            status_ = Q_HANDLED();
            break;
        }
        /* @(/2/1/3/1/1) */
        case TIME_SIG: {
            printf("%02u:%02u:%02u\n", ((RtcEvt*)e)->rtc.hours, ((RtcEvt*)e)->rtc.minutes, ((RtcEvt*)e)->rtc.seconds);
            l_CoffeeAO.alarm.real_current_time = ((RtcEvt*)e)->rtc;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/2/1/3/1/2) ...........................................................*/
QState Alarm_alarm_off(Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/1/3/1/2/0) */
        case ALARM_TOGGLE_SIG: {
            //printf("Alarm SM toggled to on.\n");
            status_ = Q_TRAN(&Alarm_alarm_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&Alarm_normal);
            break;
        }
    }
    return status_;
}
/* @(/2/1/3/1/3) ...........................................................*/
QState Alarm_alarm_on(Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/1/3/1/3/0) */
        case ALARM_TOGGLE_SIG: {
            //printf("Alarm SM toggled to off.\n");
            status_ = Q_TRAN(&Alarm_alarm_off);
            break;
        }
        /* @(/2/1/3/1/3/1) */
        case TIME_SIG: {
            //printf("%02u:%02u:%02u", ((RtcEvt*)e)->rtc.hours, ((RtcEvt*)e)->rtc.minutes, ((RtcEvt*)e)->rtc.seconds);
            /* @(/2/1/3/1/3/1/0) */
            if (((RtcEvt *)e)->rtc.hours == me->alarm_time.hours
&& ((RtcEvt *)e)->rtc.minutes == me->alarm_time.minutes
&& ((RtcEvt *)e)->rtc.seconds == 0
) {
                printf("ALARM!!!\n");
                /* asynchronously post the event to the container AO */
                QF_INT_ENABLE();
                QActive_postFIFO((QActive*)&l_CoffeeAO, Q_NEW(QEvent, BREW_SIG));
                QF_INT_DISABLE();
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Alarm_normal);
            break;
        }
    }
    return status_;
}

