/*****************************************************************************
* Model: coffeeAo.qm
* File:  src\coffee/alarm.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/3) .................................................................*/
#ifndef _ALARM_H
#define _ALARM_H

#include "qp_port.h"
#include <stdio.h>

#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))

enum AlarmClockSignals {
    TICK_SIG = Q_USER_SIG,                               /* time tick event */
    ALARM_SET_SIG,                                         /* set the alarm */
    ALARM_ON_SIG,                                      /* turn the alarm on */
    ALARM_OFF_SIG,                                    /* turn the alarm off */
    ALARM_SIG,  /* alarm event from Alarm component to AlarmClock container */
    CLOCK_12H_SIG,                             /* set the clock in 12H mode */
    CLOCK_24H_SIG,                             /* set the clock in 24H mode */
    TIME_SIG,           /* time event sent to Alarm (contains current time) */
    TERMINATE_SIG,                              /* terminate the application */
    GO_COFFEE_POT_TOGGLE_SIG,
    GO_TIME_BREW_TOGGLE_SIG,
    GO_SET_BREW_TIME_CLOCK_SIG,
    GO_SET_TIME_OF_DAY_SIG,
    GO_START_BREWING_SIG,
    GO_SET_BREW_STRENGTH_SIG,
    GO_BACK_SIG,
    ADWHEEL_SIG,
    INT_SIG,
    BREW_SIG
};

typedef struct HourAndMinuteTag {
    uint8_t hours;
    uint8_t minutes;
} HourAndMinute;

extern QActive *APP_alarmClock;

/* @(/1/1) .................................................................*/
typedef struct SetEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint8_t digit;
} SetEvt;

/* @(/1/2) .................................................................*/
typedef struct TimeEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint8_t current_time;
} TimeEvt;

/* @(/1/3) .................................................................*/
typedef struct AdEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint16_t val;
} AdEvt;

/* @(/2/1) .................................................................*/
typedef struct AlarmTag {
/* protected: */
    QFsm super;

/* public: */
    HourAndMinute alarm_time_struct;
    HourAndMinute current_time;
    uint16_t alarm_time;
} Alarm;

/* protected: */
QState Alarm_initial(Alarm * const me, QEvt const * const e);
QState Alarm_off(Alarm * const me, QEvt const * const e);
QState Alarm_on(Alarm * const me, QEvt const * const e);

/* @(/2/3) .................................................................*/
void Alarm_ctor(Alarm * me);


#define Alarm_init(me_)           QFsm_init    ((QFsm *)(me_), (QEvent *)0)
#define Alarm_dispatch(me_, e_)   QFsm_dispatch((QFsm *)(me_), e_)

#endif
